engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
    config:
    extensions:
    - .js
    - .jsx
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- dist/
- examples/
